In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
matches = pd.read_csv('matches.csv')

In [3]:
matches.head(2)

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN

In [4]:
matches=matches[[
    'id',
    'season',
    'city',
    'date',
    'team1',
    'team2',
    'toss_winner',
    'toss_decision',
    'winner',
    'venue',
    'player_of_match'
]]

In [5]:
deliveries = pd.read_csv('deliveries.csv')
deliveries.head(1)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN

In [6]:
deliveries = deliveries[[
    'match_id',
    'inning',
    'over',
    'ball',
    'batting_team',
    'bowling_team',
    'batsman',
    'bowler',
    'batsman_runs',
    'total_runs',
    'extra_runs',
    'player_dismissed'
]]

In [7]:
deliveries.head()

,match_id,inning,over,ball,batting_team,bowling_team,batsman,bowler,batsman_runs,total_runs,extra_runs,player_dismissed
0,1,1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,DA Warner,TS Mills,0,0,0,NaN
1,1,1,1,2,Sunrisers Hyderabad,Royal Challengers Bangalore,DA Warner,TS Mills,0,0,0,NaN
2,1,1,1,3,Sunrisers Hyderabad,Royal Challengers Bangalore,DA Warner,TS Mills,4,4,0,NaN
3,1,1,1,4,Sunrisers Hyderabad,Royal Challengers Bangalore,DA Warner,TS Mills,0,0,0,NaN
4,1,1,1,5,Sunrisers Hyderabad,Royal Challengers Bangalore,DA Warner,TS Mills,0,2,2,NaN

<h1>Data Understanding</h1>

In [8]:
matches.shape

(636, 11)

In [9]:
matches.columns

Index(['id', 'season', 'city', 'date', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'winner', 'venue', 'player_of_match'],
      dtype='str')

In [10]:
matches.info()

<class 'pandas.DataFrame'>
RangeIndex: 636 entries, 0 to 635
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               636 non-null    int64
 1   season           636 non-null    int64
 2   city             629 non-null    str
 3   date             636 non-null    str
 4   team1            636 non-null    str
 5   team2            636 non-null    str
 6   toss_winner      636 non-null    str
 7   toss_decision    636 non-null    str
 8   winner           633 non-null    str
 9   venue            636 non-null    str
 10  player_of_match  633 non-null    str
dtypes: int64(2), str(9)
memory usage: 134.3 KB

In [11]:
matches.isnull().sum()

id                 0
season             0
city               7
date               0
team1              0
team2              0
toss_winner        0
toss_decision      0
winner             3
venue              0
player_of_match    3
dtype: int64

In [12]:
matches = matches.fillna({'city':'Unknown'})

In [13]:
matches.isnull().sum()

id                 0
season             0
city               0
date               0
team1              0
team2              0
toss_winner        0
toss_decision      0
winner             3
venue              0
player_of_match    3
dtype: int64

In [14]:
matches = matches[matches['winner'].notnull()]

In [15]:
total_seasons = matches['season'].nunique()

total_matches = matches.shape[0]

total_teams = len(
    set(matches['team1']).union(
        set(matches['team2'])
    )
)

total_venues = matches['venue'].nunique()

total_players = len(
    set(deliveries['batsman']).union(
        set(deliveries['bowler'])
    )
)

print("Total Seasons :", total_seasons)
print("Total Matches :", total_matches)
print("Total Teams :", total_teams)
print("Total Venues :", total_venues)
print("Total Players :", total_players)

Total Seasons : 10
Total Matches : 633
Total Teams : 14
Total Venues : 35
Total Players : 495

In [16]:
deliveries.shape

(150460, 12)

In [17]:
deliveries.columns

Index(['match_id', 'inning', 'over', 'ball', 'batting_team', 'bowling_team',
       'batsman', 'bowler', 'batsman_runs', 'total_runs', 'extra_runs',
       'player_dismissed'],
      dtype='str')

In [18]:
deliveries.info()

<class 'pandas.DataFrame'>
RangeIndex: 150460 entries, 0 to 150459
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          150460 non-null  int64
 1   inning            150460 non-null  int64
 2   over              150460 non-null  int64
 3   ball              150460 non-null  int64
 4   batting_team      150460 non-null  str
 5   bowling_team      150460 non-null  str
 6   batsman           150460 non-null  str
 7   bowler            150460 non-null  str
 8   batsman_runs      150460 non-null  int64
 9   total_runs        150460 non-null  int64
 10  extra_runs        150460 non-null  int64
 11  player_dismissed  7438 non-null    str
dtypes: int64(7), str(5)
memory usage: 21.7 MB

In [19]:
deliveries.isnull().sum()

match_id                 0
inning                   0
over                     0
ball                     0
batting_team             0
bowling_team             0
batsman                  0
bowler                   0
batsman_runs             0
total_runs               0
extra_runs               0
player_dismissed    143022
dtype: int64

<h1>Team Analysis</h1>

In [20]:
# Total Wins 


team_wins = matches['winner'].value_counts()

print(team_wins)

winner
Mumbai Indians                 92
Chennai Super Kings            79
Kolkata Knight Riders          77
Royal Challengers Bangalore    73
Kings XI Punjab                70
Rajasthan Royals               63
Delhi Daredevils               62
Sunrisers Hyderabad            42
Deccan Chargers                29
Gujarat Lions                  13
Pune Warriors                  12
Rising Pune Supergiant         10
Kochi Tuskers Kerala            6
Rising Pune Supergiants         5
Name: count, dtype: int64

In [21]:
# Win Percentage


matches_played = pd.concat([
    matches['team1'],
    matches['team2']
]).value_counts()

wins = matches['winner'].value_counts()

win_percent = (
    wins / matches_played * 100
).round(2)

print(win_percent)

winner
Chennai Super Kings            60.31
Deccan Chargers                38.67
Delhi Daredevils               42.76
Gujarat Lions                  43.33
Kings XI Punjab                47.30
Kochi Tuskers Kerala           42.86
Kolkata Knight Riders          52.03
Mumbai Indians                 58.60
Pune Warriors                  26.67
Rajasthan Royals               53.85
Rising Pune Supergiant         62.50
Rising Pune Supergiants        35.71
Royal Challengers Bangalore    48.67
Sunrisers Hyderabad            55.26
Name: count, dtype: float64

In [22]:
# Toss Impact


matches['toss_match_win'] = (
    matches['toss_winner'] == matches['winner']
)

toss_impact = (
    matches['toss_match_win']
    .value_counts(normalize=True)
    *100
)

print(toss_impact)

toss_match_win
True     51.342812
False    48.657188
Name: proportion, dtype: float64

In [23]:
# Home Ground Performance


matches[matches['venue'].str.contains('Wankhede',case=False,na=False)]['winner'].value_counts()

winner
Mumbai Indians                 34
Kings XI Punjab                 5
Chennai Super Kings             4
Royal Challengers Bangalore     3
Rising Pune Supergiant          2
Rajasthan Royals                2
Kochi Tuskers Kerala            1
Deccan Chargers                 1
Pune Warriors                   1
Delhi Daredevils                1
Kolkata Knight Riders           1
Rising Pune Supergiants         1
Gujarat Lions                   1
Name: count, dtype: int64

<h1>Batting Analysis</h1>

In [24]:
# Top Run Scorers


top_runs = deliveries.groupby('batsman')['batsman_runs'].sum()

top_runs.sort_values(
    ascending=False
).head(10)

batsman
SK Raina          4548
V Kohli           4423
RG Sharma         4207
G Gambhir         4132
DA Warner         4014
RV Uthappa        3778
CH Gayle          3651
S Dhawan          3561
MS Dhoni          3560
AB de Villiers    3486
Name: batsman_runs, dtype: int64

In [25]:
# Strike Rate


batting = deliveries.groupby('batsman').agg({'batsman_runs':'sum','ball':'count'})

batting['Strike Rate'] = (batting['batsman_runs'] / batting['ball']) * 100

batting.sort_values('Strike Rate',ascending=False).head(10)

               batsman_runs  ball  Strike Rate
batsman
DL Chahar                14     6   233.333333
Umar Gul                 39    19   205.263158
RS Sodhi                  4     2   200.000000
BCJ Cutting             124    70   177.142857
AJ Tye                   53    30   176.666667
Shahid Afridi            81    46   176.086957
I Malhotra                7     4   175.000000
SN Khan                 177   103   171.844660
CR Brathwaite            95    56   169.642857
LJ Wright               106    63   168.253968

In [26]:
# Most Sixes


sixes = deliveries[deliveries['batsman_runs']==6]

sixes.groupby('batsman').size().sort_values(ascending=False).head(10)

batsman
CH Gayle          266
SK Raina          174
RG Sharma         173
DA Warner         160
V Kohli           160
AB de Villiers    158
MS Dhoni          156
YK Pathan         149
KA Pollard        148
Yuvraj Singh      141
dtype: int64

In [27]:
# Most Fours


fours = deliveries[deliveries['batsman_runs']==4]

fours.groupby('batsman').size().sort_values(ascending=False).head(10)

batsman
G Gambhir     484
SK Raina      402
DA Warner     401
S Dhawan      401
V Kohli       384
RV Uthappa    377
RG Sharma     354
V Sehwag      334
AM Rahane     320
CH Gayle      297
dtype: int64

<h1>Bowling Analysis<h1>

In [28]:
# Most Wickets


wickets = deliveries[deliveries['player_dismissed'].notnull()]

wickets.groupby('bowler').size().sort_values(ascending=False).head(10)

bowler
SL Malinga         170
A Mishra           142
DJ Bravo           137
Harbhajan Singh    136
PP Chawla          133
R Vinay Kumar      125
A Nehra            121
Z Khan             119
B Kumar            117
R Ashwin           110
dtype: int64

In [29]:
# Economy Rate


economy = deliveries.groupby('bowler').agg({'total_runs':'sum','ball':'count'})

economy['overs'] = economy['ball']/6

economy['economy'] = (economy['total_runs'] / economy['overs'])

economy.sort_values('economy').head(10)

               total_runs  ball      overs   economy
bowler
AC Gilchrist            0     1   0.166667  0.000000
N Rana                  3     6   1.000000  3.000000
NB Singh               18    25   4.166667  4.320000
Sachin Baby             8    10   1.666667  4.800000
AM Rahane               5     6   1.000000  5.000000
LA Carseldine           6     7   1.166667  5.142857
SS Mundhe               6     7   1.166667  5.142857
Mohammad Nabi          59    66  11.000000  5.363636
DJ Thornely            40    44   7.333333  5.454545
Avesh Khan             24    24   4.000000  6.000000

In [30]:
# Death Over Specialists


death = deliveries[deliveries['over'] >= 16]
death.head()

,match_id,inning,over,ball,batting_team,bowling_team,batsman,bowler,batsman_runs,total_runs,extra_runs,player_dismissed
93,1,1,16,1,Sunrisers Hyderabad,Royal Challengers Bangalore,MC Henriques,YS Chahal,0,0,0,NaN
94,1,1,16,2,Sunrisers Hyderabad,Royal Challengers Bangalore,MC Henriques,YS Chahal,0,0,0,MC Henriques
95,1,1,16,3,Sunrisers Hyderabad,Royal Challengers Bangalore,Yuvraj Singh,YS Chahal,1,1,0,NaN
96,1,1,16,4,Sunrisers Hyderabad,Royal Challengers Bangalore,DJ Hooda,YS Chahal,1,1,0,NaN
97,1,1,16,5,Sunrisers Hyderabad,Royal Challengers Bangalore,Yuvraj Singh,YS Chahal,1,1,0,NaN

In [31]:
# Death Over Wickets


death[death['player_dismissed'].notnull()].groupby('bowler').size().sort_values(ascending=False).head(10)

bowler
SL Malinga       108
DJ Bravo          79
B Kumar           65
A Nehra           63
R Vinay Kumar     60
SP Narine         60
UT Yadav          57
RP Singh          55
SR Watson         54
DW Steyn          54
dtype: int64

<h1>Venue Analysis<h1>

In [32]:
# Venue Wise Average Score


venue_score = deliveries.groupby('match_id')['total_runs'].sum().reset_index()

venue_score = venue_score.merge(
    matches[['id','venue']],
    left_on='match_id',
    right_on='id'
)

venue_score.groupby('venue')['total_runs'].mean().sort_values(ascending=False).head()

venue
Brabourne Stadium                                       349.272727
Saurashtra Cricket Association Stadium                  333.300000
Barabati Stadium                                        325.428571
Green Park                                              324.500000
Punjab Cricket Association IS Bindra Stadium, Mohali    322.272727
Name: total_runs, dtype: float64

In [33]:
# Batting Friendly Grounds


venue_score.groupby('venue')['total_runs'].mean().sort_values(ascending=False).head(1)

venue
Brabourne Stadium    349.272727
Name: total_runs, dtype: float64

In [34]:
# Bowling Friendly Grounds


venue_score.groupby('venue')['total_runs'].mean().sort_values(ascending=False).tail(1)

venue
Newlands    256.714286
Name: total_runs, dtype: float64

<h1>Match Analysis<h1>

In [35]:
# Bat First vs Chase Wins

# Create Batting First Team
matches['bat_first_team'] = matches.apply(
    lambda x: x['team1']
    if x['toss_decision'] == 'bat'
    else x['team2'],
    axis=1
)

# Create Chasing Team
matches['chasing_team'] = matches.apply(
    lambda x: x['team2']
    if x['toss_decision'] == 'bat'
    else x['team1'],
    axis=1
)

# Find Bat First Wins
bat_first_wins = (matches['winner'] == matches['bat_first_team']).sum()

print(bat_first_wins)


# Find Chase Wins
chase_wins = (matches['winner'] == matches['chasing_team']).sum()

print(chase_wins)

# Calculate Percentages
total_matches = len(matches)

bat_first_pct = round(bat_first_wins / total_matches * 100,2)

chase_pct = round(chase_wins / total_matches * 100,2)

print("Bat First Wins:", bat_first_pct)
print("Chase Wins:", chase_pct)

325
308
Bat First Wins: 51.34
Chase Wins: 48.66

In [36]:
summary = pd.DataFrame({
    'Strategy':['Bat First','Chase'],
    'Wins':[bat_first_wins,chase_wins],
    'Percentage':[bat_first_pct,chase_pct]
})

summary

    Strategy  Wins  Percentage
0  Bat First   325       51.34
1      Chase   308       48.66

<h1>Advanced Analysis

<h4>Best Finisher Batsman

In [37]:
# Filter Death Over
death_overs = deliveries[deliveries['over'] >= 16]

# Calculate Runs and Ball Faced
finisher_stats = death_overs.groupby('batsman').agg(
    Runs=('batsman_runs', 'sum'),
    Balls=('batsman_runs', 'count')
)

# Calculate Strike Rate
finisher_stats['Strike Rate'] = (finisher_stats['Runs'] / finisher_stats['Balls']) * 100

# Filter players who faced at least 100 balls
finisher_stats = finisher_stats[finisher_stats['Balls'] >= 100]

# Create Finisher Score
# finisher_stats['Finisher Score'] = (
#     finisher_stats['Runs'] * 0.7
#     +
#     finisher_stats['Strike Rate'] * 0.3
# )

# Rank Best Finishers
best_finishers = finisher_stats.sort_values('Runs',ascending=False)

pd.DataFrame(best_finishers).head(10)

                Runs  Balls  Strike Rate
batsman
MS Dhoni        2076   1224   169.607843
KA Pollard      1352    838   161.336516
RG Sharma       1314    748   175.668449
AB de Villiers  1203    570   211.052632
V Kohli          993    546   181.868132
YK Pathan        930    584   159.246575
Yuvraj Singh     883    516   171.124031
JP Duminy        869    518   167.760618
SK Raina         767    458   167.467249
RA Jadeja        753    576   130.729167

<h4>Best Powerplay Batsman

In [70]:
# Filter Powerplay Overs
powerplay = deliveries[deliveries['over'] <= 6]

# Calculate Runs
powerplay_runs = powerplay.groupby('batsman')['batsman_runs'].sum()
powerplay_runs.sort_values(ascending=False).head(10)

# Calculate Balls Faced
balls_faced = powerplay.groupby('batsman').size()

# Create Batting Summary
powerplay_stats = pd.DataFrame({
    'Runs': powerplay.groupby('batsman')['batsman_runs'].sum(),
    'Balls': powerplay.groupby('batsman').size()
})

# Calculate Strike Rate
powerplay_stats['Strike Rate'] = (
    powerplay_stats['Runs']
    /
    powerplay_stats['Balls']
) * 100

# Runs Score
powerplay_stats['Runs Score'] = (
    powerplay_stats['Runs']
    /
    powerplay_stats['Runs'].max()
) * 100

# Strike Rate Score
powerplay_stats['SR Score'] = (
    powerplay_stats['Strike Rate']
    /
    powerplay_stats['Strike Rate'].max()
) * 100

# Impact Score
powerplay_stats['Impact Score'] = (
    powerplay_stats['Runs Score'] * 0.6
    +
    powerplay_stats['SR Score'] * 0.4
)

# Filter players with at least 100 balls
powerplay_stats = powerplay_stats[
    powerplay_stats['Balls'] >= 200
]

In [71]:
# Rank Best Powerplay Batsmen

In [72]:
# By Runs 

powerplay_stats.sort_values(
    'Runs',
    ascending=False
).head(10)

             Runs  Balls  Strike Rate  Runs Score   SR Score  Impact Score
batsman
G Gambhir    2213   1874   118.089648  100.000000  33.739899     73.495960
DA Warner    1968   1476   133.333333   88.929056  38.095238     68.595529
S Dhawan     1792   1580   113.417722   80.976051  32.405063     61.547656
CH Gayle     1778   1395   127.455197   80.343425  36.415771     62.772363
V Sehwag     1593   1160   137.327586   71.983732  39.236453     58.884821
PA Patel     1521   1366   111.346999   68.730230  31.813428     53.963510
RV Uthappa   1506   1255   120.000000   68.052418  34.285714     54.545736
BB McCullum  1502   1233   121.816707   67.871667  34.804773     54.644910
M Vijay      1494   1338   111.659193   67.510167  31.902627     53.267151
AM Rahane    1417   1292   109.674923   64.030728  31.335692     50.952713

In [73]:
# By Strike Rate

powerplay_stats.sort_values(
    'Strike Rate',
    ascending=False
).head(10)

              Runs  Balls  Strike Rate  Runs Score   SR Score  Impact Score
batsman
YK Pathan      342    241   141.908714   15.454135  40.545347     25.490620
F du Plessis   507    364   139.285714   22.910077  39.795918     29.664413
V Sehwag      1593   1160   137.327586   71.983732  39.236453     58.884821
WP Saha        443    332   133.433735   20.018075  38.123924     27.260415
DA Warner     1968   1476   133.333333   88.929056  38.095238     68.595529
JD Ryder       440    334   131.736527   19.882512  37.639008     26.985111
SK Raina      1280    978   130.879346   57.840036  37.394099     49.661661
KP Pietersen   392    301   130.232558   17.713511  37.209302     25.511828
SA Asnodkar    278    216   128.703704   12.562133  36.772487     22.246274
AC Gilchrist  1385   1080   128.240741   62.584727  36.640212     52.206921

<h1>MVP (Most Valuable Player) Score

In [42]:
# Calculate Batting Runs
runs = deliveries.groupby('batsman')['batsman_runs'].sum()
runs = runs.reset_index()
runs.columns = ['Player', 'Runs']

# Calculate Wickets
wickets = deliveries[
    deliveries['player_dismissed'].notnull()
]

wickets = wickets.groupby('bowler').size().reset_index()

wickets.columns = ['Player', 'Wickets']

# Calculate Player of Match Awards
awards = matches.groupby(
    'player_of_match'
).size().reset_index()

awards.columns = ['Player', 'Awards']

# Merge Everything
mvp = runs.merge(
    wickets,
    on='Player',
    how='outer'
)

mvp = mvp.merge(
    awards,
    on='Player',
    how='outer'
)

mvp.fillna(0, inplace=True)

# Normalize Values
mvp['Runs_Score'] = (
    mvp['Runs']
    /
    mvp['Runs'].max()
) * 100

mvp['Wicket_Score'] = (
    mvp['Wickets']
    /
    mvp['Wickets'].max()
) * 100

mvp['Award_Score'] = (
    mvp['Awards']
    /
    mvp['Awards'].max()
) * 100

# Create MVP Score
mvp['MVP_Score'] = (
    mvp['Runs_Score'] * 0.5
    +
    mvp['Wicket_Score'] * 0.3
    +
    mvp['Award_Score'] * 0.2
)

# Rank Players
mvp = mvp.sort_values(
    'MVP_Score',
    ascending=False
)

mvp.head(10)

,Player,Runs,Wickets,Awards,Runs_Score,Wicket_Score,Award_Score,MVP_Score
393,SK Raina,4548.0,30.0,14.0,100.000000,17.647059,77.777778,70.849673
342,RG Sharma,4207.0,16.0,14.0,92.502199,9.411765,77.777778,64.630184
93,CH Gayle,3651.0,19.0,18.0,80.277045,11.176471,100.000000,63.491464
457,V Kohli,4423.0,5.0,11.0,97.251539,2.941176,61.111111,61.730345
111,DA Warner,4014.0,0.0,15.0,88.258575,0.000000,83.333333,60.795954
145,G Gambhir,4132.0,0.0,13.0,90.853122,0.000000,72.222222,59.871006
480,YK Pathan,2922.0,45.0,16.0,64.248021,26.470588,88.888889,57.842965
410,SR Watson,2628.0,100.0,10.0,57.783641,58.823529,55.555556,57.649991
24,AB de Villiers,3486.0,0.0,15.0,76.649077,0.000000,83.333333,54.991205
273,MS Dhoni,3560.0,0.0,13.0,78.276165,0.000000,72.222222,53.582527

In [43]:
deliveries.to_csv('deliveri.csv',index=False)

In [44]:
matches.to_csv('match2.csv',index=False)

In [45]:
deliveries['player_dismissed'].notnull().sum()

np.int64(7438)

In [46]:
deliveries[deliveries['player_dismissed'].notnull()] \
.groupby('bowler') \
.size() \
.sort_values(ascending=False) \
.head(10)

bowler
SL Malinga         170
A Mishra           142
DJ Bravo           137
Harbhajan Singh    136
PP Chawla          133
R Vinay Kumar      125
A Nehra            121
Z Khan             119
B Kumar            117
R Ashwin           110
dtype: int64

In [47]:
deliveries['player_dismissed'].count()

np.int64(7438)

In [48]:
deliveries['player_dismissed'].notna().sum()

np.int64(7438)

In [49]:
deliveries[
    deliveries['player_dismissed'].notna()
].groupby('bowler').size().sort_values(ascending=False).head(10)

bowler
SL Malinga         170
A Mishra           142
DJ Bravo           137
Harbhajan Singh    136
PP Chawla          133
R Vinay Kumar      125
A Nehra            121
Z Khan             119
B Kumar            117
R Ashwin           110
dtype: int64

In [69]:
match_score = deliveries.groupby(
    'match_id'
)['total_runs'].sum().reset_index()

venue_score = match_score.merge(
    matches[['id','venue']],
    left_on='match_id',
    right_on='id'
)

venue_avg = venue_score.groupby(
    'venue'
)['total_runs'].mean().reset_index()

venue_avg.sort_values(
    'total_runs',
    ascending=False
).head()

                                                venue  total_runs
1                                   Brabourne Stadium  349.272727
25             Saurashtra Cricket Association Stadium  333.300000
0                                    Barabati Stadium  325.428571
9                                          Green Park  324.500000
21  Punjab Cricket Association IS Bindra Stadium, ...  322.272727

In [51]:
venue_avg.to_csv("venue_avg.csv",index=False)

In [52]:
mvp.to_csv("mvp.csv",index=False)

In [53]:
death_overs = deliveries[
    deliveries['over'] >= 16
]

In [54]:
death_overs.head()

,match_id,inning,over,ball,batting_team,bowling_team,batsman,bowler,batsman_runs,total_runs,extra_runs,player_dismissed
93,1,1,16,1,Sunrisers Hyderabad,Royal Challengers Bangalore,MC Henriques,YS Chahal,0,0,0,NaN
94,1,1,16,2,Sunrisers Hyderabad,Royal Challengers Bangalore,MC Henriques,YS Chahal,0,0,0,MC Henriques
95,1,1,16,3,Sunrisers Hyderabad,Royal Challengers Bangalore,Yuvraj Singh,YS Chahal,1,1,0,NaN
96,1,1,16,4,Sunrisers Hyderabad,Royal Challengers Bangalore,DJ Hooda,YS Chahal,1,1,0,NaN
97,1,1,16,5,Sunrisers Hyderabad,Royal Challengers Bangalore,Yuvraj Singh,YS Chahal,1,1,0,NaN

In [57]:
runs = death_overs.groupby(
    'batsman'
)['batsman_runs'].sum()

print(runs.head())

batsman
A Ashish Reddy    214
A Chandila          4
A Chopra            1
A Choudhary        25
A Flintoff         25
Name: batsman_runs, dtype: int64

In [58]:
balls = death_overs.groupby(
    'batsman'
).size()

In [59]:
finisher = pd.DataFrame({
    'Runs': runs,
    'Balls': balls
})

finisher.head()

                Runs  Balls
batsman
A Ashish Reddy   214    148
A Chandila         4      7
A Chopra           1      2
A Choudhary       25     20
A Flintoff        25     18

In [60]:
finisher['Strike Rate'] = (
    finisher['Runs']
    /
    finisher['Balls']
) * 100

In [61]:
finisher = finisher[
    finisher['Balls'] >= 100
]

In [62]:
finisher['Runs Score'] = (
    finisher['Runs']
    /
    finisher['Runs'].max()
) * 100

In [63]:
finisher['SR Score'] = (
    finisher['Strike Rate']
    /
    finisher['Strike Rate'].max()
) * 100

In [64]:
finisher['Finisher Score'] = (
    finisher['Runs Score'] * 0.6
    +
    finisher['SR Score'] * 0.4
)

In [65]:
best_finishers = finisher.sort_values(
    'Finisher Score',
    ascending=False
)

In [66]:
best_finishers[
    [
        'Runs',
        'Balls',
        'Strike Rate',
        'Finisher Score'
    ]
].head(10)

                Runs  Balls  Strike Rate  Finisher Score
batsman
MS Dhoni        2076   1224   169.607843       92.145127
AB de Villiers  1203    570   211.052632       74.768786
RG Sharma       1314    748   175.668449       71.270650
KA Pollard      1352    838   161.336516       69.652639
V Kohli          993    546   181.868132       63.168195
Yuvraj Singh     883    516   171.124031       57.952716
YK Pathan        930    584   159.246575       57.060009
JP Duminy        869    518   167.760618       56.910637
DA Miller        672    360   186.666667       54.800186
SK Raina         767    458   167.467249       53.907059

In [67]:
best_finishers.to_csv(
    "best_finishers.csv"
)

In [75]:
powerplay_stats.to_csv("powerplay_stats.csv")